version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - "3000:3000"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/socialmedia
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ./src:/app/src
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./src:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: socialmedia
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge